name: main 브랜치 푸시 워크플로우

on:
  push:
    branches:
      - "main"

jobs:
  detect-release:
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'devneopark' }}
    outputs:
      changes-json: ${{ steps.check.outputs.changes-json }}

    steps:
      - name: "0단계: 브랜치 체크아웃"
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: "1단계: 변경된 모듈 감지"
        id: check
        run: |
          CHANGED=$(git diff-tree --no-commit-id --name-only -r HEAD)
          echo "$CHANGED"
          
          CHANGED_MODULES=$(echo "$CHANGED" | grep 'modules/' | awk -F/ '{print $1"/"$2}' | sort -u)
          echo "변경된 모듈:"
          echo "$CHANGED_MODULES"
          
          if [[ -n "${CHANGED_MODULES//[$'\n\r[:space:]']}" ]]; then
            CHANGES_JSON="[$(echo "$CHANGED_MODULES" | sed 's/.*/"&"/' | paste -sd, -)]"
          else
            CHANGES_JSON="[]"
          fi
          
          echo "changes-json=$CHANGES_JSON" >> $GITHUB_OUTPUT

  release:
    needs: detect-release
    if: ${{ needs.detect-release.outputs.changes-json != '[]' }}
    strategy:
      matrix:
        module: ${{ fromJSON(needs.detect-release.outputs.changes-json) }}
    uses: ./.github/workflows/release.yml
    with:
      module: ${{ matrix.module }}
    secrets: inherit
