name: main 브랜치 푸시 워크플로우

on:
  push:
    branches:
      - "main"

jobs:
  detect-release:
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'devneopark' }}
    outputs:
      is-foo-changed: ${{ steps.check.outputs.is-foo-changed }}
      is-bar-changed: ${{ steps.check.outputs.is-bar-changed }}

    steps:
      - name: "0단계: 브랜치 체크아웃"
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: "1단계: 변경된 모듈 감지"
        id: check
        run: |
          CHANGED=$(git diff-tree --no-commit-id --name-only -r HEAD)
          echo "$CHANGED"
          
          CHANGED_MODULES=$(echo "$CHANGED" | grep 'modules/' | awk -F/ '{print $1"/"$2"/"$3}' | sort -u)
          echo "변경된 모듈:"
          echo "'$CHANGED_MODULES'"
          
          if [[ -n "${CHANGED_MODULES//[$'\n\r[:space:]']}" ]]; then
            CHANGES_JSON="[$(echo "$CHANGED_MODULES" | sed 's/.*/"&"/' | paste -sd, -)]"
          else
            CHANGES_JSON="[]"
          fi
          
          echo "json: $CHANGES_JSON"

#          if grep -q '^foo/' <<< "$CHANGED"; then
#            echo "foo 모듈에서 변경사항이 있습니다."
#            echo "is-foo-changed=true" >> $GITHUB_OUTPUT
#          fi
#          if grep -q '^bar/' <<< "$CHANGED"; then
#            echo "bar 모듈에서 변경사항이 있습니다."
#            echo "is-bar-changed=true" >> $GITHUB_OUTPUT
#          fi

  release-foo:
    needs: detect-release
    if: ${{ needs.detect-release.outputs.is-foo-changed == 'true' }}
    uses: ./.github/workflows/release.yml
    with:
      module: foo
    secrets: inherit

  release-bar:
    needs: detect-release
    if: ${{ needs.detect-release.outputs.is-bar-changed == 'true' }}
    uses: ./.github/workflows/release.yml
    with:
      module: bar
    secrets: inherit
